### ISSUE TITLE
metabolite inputs

### ISSUE THREAD

**Issue by DominikMartinat** [BioDataFuse/pyBiodatafuse#8] opened 2023-10-30 15:52 UTC
Create functions for metabolite inputs (inchikeys, SMILES, something else perhaps?) and try it on MolMeDB maybe.

**Comment by egonw** [comment] 2023-10-31 09:02
@DominikMartinat, will you start a https://github.com/BioDataFuse/pyBiodatafuse/blob/main/examples/workflow.ipynb equivalent for InChIKeys?

**Comment by DominikMartinat** [comment] 2023-10-31 09:37
@egonw Sure. I will try to make anotator first, to familiarise myself witht the code, then I will go for InChIKeys.

**Comment by tabbassidaloii** [comment] 2023-11-01 09:25
The current ID mapper is based on BridgeDb and I can confirm it does mapping for metabolites. So you don't need to add a new module for metabolites or a list of IDs.
The streamlit application should be modified so the user can also query for metabolites.
we are looking for an [alternative for the streamlit](https://github.com/BioDataFuse/biodatafuseApp/issues/11)

**Comment by DominikMartinat** [comment] 2023-11-01 09:33
I found out, we have in MolMeDB some external mappings of molecules that are not in BridgeDB yet eg. [Cephaloridine](https://molmedb.upol.cz/mol/MM00638). Should I make some list of mappings to InChIKeys we have for BridgeDB? @egonw

**Comment by egonw** [comment] 2023-11-01 13:00
@DominikMartinat, how many chemicals are missing? If not more than a few thousand, we can also add them to Wikidata

**Comment by DominikMartinat** [comment] 2023-11-02 13:16
@egonw Im done comparing mappings, using common inchikeys and it is aprox. 7000 ChEMBL compound ids, few ChEBI ids, 100 DrugBank ids and 400 PubChem compound ids. In MolMeDB we are missing much more, so I am going to propose to our team filling the gaps using BridgeDB.

Our ChEBI and ChEMBL ids are bit mess considering formating, so I will need to fix this before I send the mappings.

**Comment by tabbassidaloii** [comment] 2023-11-02 16:40
@egonw @DominikMartinat Shall we make another issue for the discussion as the importing of the metabolite inputs is done and I want to close this issue?

**Comment by tabbassidaloii** [comment] 2023-11-03 15:59
@DominikMartinat @egonw, the metabolite import is now supported, shall I close this issue?
We can open another issue for the mapping in MolMeDB?

**Comment by egonw** [comment] 2023-11-03 16:59
Where can I see it in action?

**Comment by DominikMartinat** [comment] 2023-11-03 17:07
@tabbassidaloii I think this is more BridgeDB issue. I will send our mappings there when I get our problems with ChEMBL and ChEBI ids formatting solved.

**Comment by egonw** [comment] 2023-11-04 08:25
> eg. [Cephaloridine](https://molmedb.upol.cz/mol/MM00638).

(I'm catching up a bit) This compound is in Wikidata, actually: https://www.wikidata.org/wiki/Q5063323 and as such should (tm) be in BridgeDb too, but not the subtle chemical change: the MolMeDB structure is positively charged, while Wikidata has the neutral form.

It sounds like we have to make effort with restoring the BridgeDb Identifier Mapping Service in anger.

**Comment by tabbassidaloii** [comment] 2023-11-07 11:24
> Where can I see it in action?

See an example [here](https://github.com/BioDataFuse/pyBiodatafuse/blob/main/examples/metabolite_workflow.ipynb)

**Comment by tabbassidaloii** [comment] 2023-11-17 09:18
To be implemented in the app

**Comment by tabbassidaloii** [comment] 2024-08-09 12:18
> To be implemented in the app

Done

**Comment by YojanaGadiya** [comment] 2024-08-09 12:19
Closing due to low activity

**Closed by YojanaGadiya** 2024-08-09 12:19 UTC
Labels: bug, biohack2023, input type
